package interview.lld.loggingframework;

/*
A logging framework is a software library or tool that provides a standardized way to record, format, filter, and route log messages
generated by an application during its execution.
Example : Frameworks like Log4j, SLF4J, and java.util.logging power millions of production services.

Requirement:
    - Logging Level : DEBUG, INFO, WARN, ERROR and FATAL
    - writing log multiple destinations, including the console and file outputs.
    - input min : log level, timestamp
    - Thread safe
    - Asynchronous logging
    - logger configuration

Core Entities:
    - LogLevel
    - LogMessage
    - Logger
    - LogAppender : FileAppender, ConsoleAppender
    - LogFormatter
    - AsyncLogProcessor
    - LogManager

Design Pattern:
    - Strategy
    - Factory
    - Producer Consumer
    - Chain of Responsibility
    - Facade
    - Singleton
 */

import interview.lld.loggingframework.enums.LogLevel;
import interview.lld.loggingframework.strategy.ConsoleAppender;

public class MainLoggingFramework {
    static void main() {
        // --- 1. Initial Configuration ---
        LogManager logManager = LogManager.getInstance();
        Logger rootLogger = logManager.getRootLogger();
        rootLogger.setLevel(LogLevel.INFO); // Set global minimum level to INFO

        // Add a console appender to the root logger
        rootLogger.addAppender(new ConsoleAppender());

        System.out.println("--- Initial Logging Demo ---");
        Logger mainLogger = logManager.getLogger("com.example.Main");
        mainLogger.info("Application starting up.");
        mainLogger.debug("This is a debug message, it should NOT appear."); // Below root level
        mainLogger.warn("This is a warning message.");

        // --- 2. Hierarchy and Additivity Demo ---
        System.out.println("\n--- Logger Hierarchy Demo ---");
        Logger dbLogger = logManager.getLogger("com.example.db");
        // dbLogger inherits level and appenders from root
        dbLogger.info("Database connection pool initializing.");

        // Let's create a more specific logger and override its level
        Logger serviceLogger = logManager.getLogger("com.example.service.UserService");
        serviceLogger.setLevel(LogLevel.DEBUG); // More verbose logging for this specific service
        serviceLogger.info("User service starting.");
        serviceLogger.debug("This debug message SHOULD now appear for the service logger.");

        // --- 3. Dynamic Configuration Change ---
        System.out.println("\n--- Dynamic Configuration Demo ---");
        System.out.println("Changing root log level to DEBUG...");
        rootLogger.setLevel(LogLevel.DEBUG);
        mainLogger.debug("This debug message should now be visible.");

        try {
            Thread.sleep(500);
            logManager.shutdown();
        } catch (Exception e) {
            System.out.println("Caught exception");
        }
    }
}
